# Стандартные параметры сканера.

# nmap-append = '-T3'
# verbose = 1
# max-scans = 30

# Глобальные параметры.
# [global]
# username-wordlist = '/usr/share/seclists/Usernames/cirt-default-usernames.txt'

# Параметры плагина перебора дерикторий.
# [dirbuster]
# threads = 50
# wordlist = [
# 	'/usr/share/seclists/Discovery/Web-Content/common.txt',
# 	'/usr/share/seclists/Discovery/Web-Content/big.txt',
# 	'/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt'
# ]
